//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardenClassLibrary.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuardenDB : DbContext
    {
        public GuardenDB()
            : base("name=GuardenDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAnswer> tblAnswers { get; set; }
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblArea_Photo_Archive> tblArea_Photo_Archive { get; set; }
        public virtual DbSet<tblPlant> tblPlants { get; set; }
        public virtual DbSet<tblPlant_Photo_Archive> tblPlant_Photo_Archive { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblResponse> tblResponses { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUser_Preferred_Categories> tblUser_Preferred_Categories { get; set; }
    }
}
