//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardenClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArea()
        {
            this.tblArea_Photo_Archive = new HashSet<tblArea_Photo_Archive>();
            this.tblPlants = new HashSet<tblPlant>();
        }
    
        public int Area_ID { get; set; }
        public string Area_Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography Area_Location { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string sunExposure { get; set; }
        public Nullable<bool> isInDoor { get; set; }
        public Nullable<int> Clicks { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArea_Photo_Archive> tblArea_Photo_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlant> tblPlants { get; set; }
    }
}
