//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardenClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea_Photo_Archive
    {
        public string Area_Photo { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public int Photo_ID { get; set; }
    
        public virtual tblArea tblArea { get; set; }
    }
}
