//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardenClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAnswer()
        {
            this.tblResponses = new HashSet<tblResponse>();
        }
    
        public int Answer_ID { get; set; }
        public string Answer_Content { get; set; }
        public Nullable<int> Answer_Votes { get; set; }
        public string Answer_Photo { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResponse> tblResponses { get; set; }
    }
}
