//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardenClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlant()
        {
            this.tblPlant_Photo_Archive = new HashSet<tblPlant_Photo_Archive>();
        }
    
        public int Plant_ID { get; set; }
        public string Plant_Name { get; set; }
        public string Plant_Category { get; set; }
        public string Plant_Lifecycle_Level { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<System.DateTime> LastWatering { get; set; }
        public Nullable<System.DateTime> PlantWaterCycle { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlant_Photo_Archive> tblPlant_Photo_Archive { get; set; }
    }
}
