//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardenClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResponse
    {
        public int Response_ID { get; set; }
        public string Response_Content { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<int> Answer_ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual tblAnswer tblAnswer { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
